# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Armnn::pipeCommon Armnn::pipeClient Armnn::armnnTestUtils Armnn::fmt Armnn::Armnn Armnn::armnnUtils)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target Armnn::pipeCommon
add_library(Armnn::pipeCommon STATIC IMPORTED)

set_target_properties(Armnn::pipeCommon PROPERTIES
  INTERFACE_LINK_LIBRARIES "-L/home/arm-user/build/acl/aarch64_build/opencl-1.2-stubs;Armnn::fmt"
)

# Create imported target Armnn::pipeClient
add_library(Armnn::pipeClient STATIC IMPORTED)

set_target_properties(Armnn::pipeClient PROPERTIES
  INTERFACE_LINK_LIBRARIES "-L/home/arm-user/build/acl/aarch64_build/opencl-1.2-stubs;Armnn::pipeCommon"
)

# Create imported target Armnn::armnnTestUtils
add_library(Armnn::armnnTestUtils SHARED IMPORTED)

set_target_properties(Armnn::armnnTestUtils PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/arm-user/source/armnn/src/armnnTestUtils/include"
  INTERFACE_LINK_LIBRARIES "-L/home/arm-user/build/acl/aarch64_build/opencl-1.2-stubs;Armnn::Armnn"
)

# Create imported target Armnn::fmt
add_library(Armnn::fmt STATIC IMPORTED)

set_target_properties(Armnn::fmt PROPERTIES
  INTERFACE_LINK_LIBRARIES "-L/home/arm-user/build/acl/aarch64_build/opencl-1.2-stubs"
)

# Create imported target Armnn::Armnn
add_library(Armnn::Armnn SHARED IMPORTED)

set_target_properties(Armnn::Armnn PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-fopenmp"
  INTERFACE_INCLUDE_DIRECTORIES "/home/arm-user/source/armnn/include"
  INTERFACE_LINK_LIBRARIES "-L/home/arm-user/build/acl/aarch64_build/opencl-1.2-stubs;Armnn::fmt;Armnn::armnnUtils;Armnn::pipeCommon;Armnn::pipeClient;dl;-lgomp;\$<\$<CONFIG:DEBUG>:/home/arm-user/build/acl/aarch64_build/libarm_compute-static.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:/home/arm-user/build/acl/aarch64_build/libarm_compute-static.a>"
)

# Create imported target Armnn::armnnUtils
add_library(Armnn::armnnUtils STATIC IMPORTED)

set_target_properties(Armnn::armnnUtils PROPERTIES
  INTERFACE_LINK_LIBRARIES "-L/home/arm-user/build/acl/aarch64_build/opencl-1.2-stubs"
)

# Import target "Armnn::pipeCommon" for configuration "Release"
set_property(TARGET Armnn::pipeCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Armnn::pipeCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/arm-user/build/armnn/aarch64_build/profiling/common/src/libpipeCommon.a"
  )

# Import target "Armnn::pipeClient" for configuration "Release"
set_property(TARGET Armnn::pipeClient APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Armnn::pipeClient PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/arm-user/build/armnn/aarch64_build/profiling/client/src/libpipeClient.a"
  )

# Import target "Armnn::armnnTestUtils" for configuration "Release"
set_property(TARGET Armnn::armnnTestUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Armnn::armnnTestUtils PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/arm-user/build/armnn/aarch64_build/libarmnnTestUtils.so.3.0"
  IMPORTED_SONAME_RELEASE "libarmnnTestUtils.so.3"
  )

# Import target "Armnn::fmt" for configuration "Release"
set_property(TARGET Armnn::fmt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Armnn::fmt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/arm-user/build/armnn/aarch64_build/third-party/fmt/libfmt.a"
  )

# Import target "Armnn::Armnn" for configuration "Release"
set_property(TARGET Armnn::Armnn APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Armnn::Armnn PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/arm-user/build/armnn/aarch64_build/libarmnn.so.35.0"
  IMPORTED_SONAME_RELEASE "libarmnn.so.35"
  )

# Import target "Armnn::armnnUtils" for configuration "Release"
set_property(TARGET Armnn::armnnUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Armnn::armnnUtils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/arm-user/build/armnn/aarch64_build/libarmnnUtils.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
